"""Add discount, tax, shipping_fee to Order

Revision ID: 5304f24e1468
Revises: 77c388fec391
Create Date: 2025-07-31 14:17:09.015755

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5304f24e1468'
down_revision = '77c388fec391'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('shipping_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('shipping_fee')
        batch_op.drop_column('tax')
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
