"""Added superadmin, staff

Revision ID: 875a976337db
Revises: 5304f24e1468
Create Date: 2025-08-02 23:27:26.496190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875a976337db'
down_revision = '5304f24e1468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_logins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_logins', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
